In [2]:
import numpy as np

In [4]:
np1 = np.array([1,2,3])
np2 = np.array([3,4,5])

In [7]:
print(np1+np2)

[4 6 8]


In [9]:
print(np1.ndim, np1.shape, np1.dtype)

1 (3,) int64


## 改變 array 的形狀

In [11]:
np3 = np.array([1,2,3,4,5,6])
np4 = np3.reshape([2,3])

In [12]:
print(np4)

[[1 2 3]
 [4 5 6]]


In [14]:
print(np4.ndim, np4.shape)

2 (2, 3)


In [22]:
np5 = np3.reshape([-1,1])
print(np5)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [16]:
print(np5.ndim, np5.shape)

2 (6, 1)


In [20]:
a = np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


## 改變元素的資料型別

In [23]:
print(np3)

[1 2 3 4 5 6]


In [25]:
print(np3.dtype)

int64


In [27]:
np6 = np3.astype(float)

In [28]:
print(np6.dtype)

float64


In [29]:
np7 = np3.astype(str)
print(np7)

['1' '2' '3' '4' '5' '6']


## 建立指定形狀的array

- 建立全部都是0的array

In [31]:
ar1 = np.zeros([2,3])
ar1

array([[0., 0., 0.],
       [0., 0., 0.]])

- 建立全部都是1的array

In [33]:
ar2 = np.ones([2,3])
ar2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
ar3 = np.ones([2,3,2])
ar3

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## 索引與切片

- one dimension slicing

In [37]:
d1 = np.array([1,2,3,4,5,6])
print(d1[2])

3


In [38]:
d2 = d1.reshape([2,3])
d2

array([[1, 2, 3],
       [4, 5, 6]])

- two dimension slicing

In [39]:
print(d2[1,0])

4


In [40]:
print(d2[:,1])

[2 5]


- use booling mask

In [41]:
np3 = np.array(range(1,7))
np3

array([1, 2, 3, 4, 5, 6])

In [42]:
print(np3 > 3)

[False False False  True  True  True]


In [43]:
print(np3[np3 > 3])

[4 5 6]


## use np.where(condition)

In [44]:
a = np.array([2,4,6,8,10])

In [45]:
print(np.where(a > 5)) # return the index in the array

(array([2, 3, 4]),)


In [47]:
print(a[np.where(a > 5)])

[ 6  8 10]


## np.random

- get random numbers from [0,1) to fill a 3 by 2 array

In [48]:
np.random.rand(3,2)

array([[0.59384326, 0.15593467],
       [0.11122573, 0.1231607 ],
       [0.81257938, 0.86851252]])

- get random numbers from normal distribution to fill a 3 by 2 array

In [49]:
np.random.randn(3,2)

array([[-2.28538272,  0.06597759],
       [ 2.16993273,  0.20699801],
       [ 0.58020134,  0.38189352]])

## np.linspance
- np.linspace(start, stop, num-50, endpoint=True)
- 回傳指定範圍內均勻間格的數字
- if the endpoint=True, the return value include the stop

In [50]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [51]:
np.linspace(2.0, 3.0, num=5, endpoint = False)

array([2. , 2.2, 2.4, 2.6, 2.8])

## 陣列的堆疊
- vstack: vertical
- hstack: horizontal

In [52]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1.shape)

(3,)


In [54]:
res = np.vstack((arr1, arr2))
print(res)

[[1 2 3]
 [4 5 6]]


In [55]:
print(res.shape)

(2, 3)


In [57]:
arr1 = np.array([[1,2], [3,4], [5,6]])
arr2 = np.array([[7,8], [9,0], [0,1]])

In [58]:
print(arr1.shape)

(3, 2)


In [59]:
res = np.hstack((arr1, arr2))

In [60]:
print(res)

[[1 2 7 8]
 [3 4 9 0]
 [5 6 0 1]]


In [61]:
print(res.shape)

(3, 4)


## 陣列的連接
- np.concatenate((a1, a2,...), axis = 0)

- When axis = 0：沿垂直方向

In [62]:
arr1 = np.array([[1,2], [3,4], [5,6]])
arr2 = np.array([[7,8], [9,0], [0,1]])
print(arr1.shape)

(3, 2)


In [63]:
res = np.concatenate((arr1, arr2), axis = 0)

In [64]:
print(res)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]
 [0 1]]


In [65]:
print(res.shape)

(6, 2)


- When axis = 1：沿水平方向

In [66]:
res = np.concatenate((arr1, arr2), axis = 1)

In [67]:
print(res)

[[1 2 7 8]
 [3 4 9 0]
 [5 6 0 1]]


In [68]:
print(res.shape)

(3, 4)


## axis is really important

- 沿垂直方向取值

In [70]:
arr1 = np.array([[1,2], [3,4], [5,6]])
np.sum(arr1, axis = 0)

array([ 9, 12])

- 沿水平方向取值

In [72]:
arr1 = np.array([[1,2], [3,4], [5,6]])
np.mean(arr1, axis = 1)

array([1.5, 3.5, 5.5])